// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1cOd9m2CRTbWiZXWXuwOyVPTbR6UFKI0',
    appId: '1:1068018762929:web:50e88bd397ac24528a4e90',
    messagingSenderId: '1068018762929',
    projectId: 'kitin-fbed4',
    authDomain: 'kitin-fbed4.firebaseapp.com',
    storageBucket: 'kitin-fbed4.appspot.com',
    measurementId: 'G-ZHFDSPEKZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUFJMtCAZ-coxaig44nIrJqip8MIdpHjU',
    appId: '1:1068018762929:android:63d9153ceab80f8a8a4e90',
    messagingSenderId: '1068018762929',
    projectId: 'kitin-fbed4',
    storageBucket: 'kitin-fbed4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMEGGlD6gy4SJpsx4KxinxvoUibao2fc',
    appId: '1:1068018762929:ios:9e92af2278bd54298a4e90',
    messagingSenderId: '1068018762929',
    projectId: 'kitin-fbed4',
    storageBucket: 'kitin-fbed4.appspot.com',
    iosClientId: '1068018762929-nrrjr47qldn3a2nddb9c8o17u5lfrs57.apps.googleusercontent.com',
    iosBundleId: 'kitin.kyro.edu.kitin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQMEGGlD6gy4SJpsx4KxinxvoUibao2fc',
    appId: '1:1068018762929:ios:9e92af2278bd54298a4e90',
    messagingSenderId: '1068018762929',
    projectId: 'kitin-fbed4',
    storageBucket: 'kitin-fbed4.appspot.com',
    iosClientId: '1068018762929-nrrjr47qldn3a2nddb9c8o17u5lfrs57.apps.googleusercontent.com',
    iosBundleId: 'kitin.kyro.edu.kitin',
  );
}
